<?xml version = '1.0' encoding = 'UTF-8'?>
<!--User Editing Not Allowed for Sections: oracle-xsl-mapper:schema, top level xsl:params, version attribute of the stylesheet element. GENERATED BY OIC MAPPER, DO NOT DELETE THIS LINE-->
<!--User Editing Not Allowed for Sections: oracle-xsl-mapper:schema, top level xsl:params, version attribute of the stylesheet element. GENERATED BY OIC MAPPER, DO NOT DELETE THIS LINE--><xsl:stylesheet xmlns:nssrcmpr="http://www.oracle.com/2014/03/ics/schedule" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:nstrgmpr="http://xmlns.oracle.com/cloud/adapter/stagefile/writeLocationStage_REQUEST/types" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ignore01="http://www.oracle.com/XSL/Transform/java" xmlns:nsmpr0="http://xmlns.oracle.com/cloud/adapter/REST/getLocation_REQUEST/types" xmlns:nsmpr1="http://www.oracle.com/2014/03/ic/integration/metadata" xmlns:ns25="http://xmlns.oracle.com/cloud/adapter/stagefile/writeLocationStage/types" xmlns:ns23="http://xmlns.oracle.com/cloud/adapter/REST/getLocation/types" version="2.0" xml:id="id_1" exclude-result-prefixes=" nssrcmpr ora oracle-xsl-mapper dvm oraext xsi xsd fn xp20 xsl ignore01 nsmpr0 nsmpr1" ignore01:ignorexmlids="true" xmlns:xml="http://www.w3.org/XML/1998/namespace">
        <oracle-xsl-mapper:schema xml:id="id_2">
              <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
              <oracle-xsl-mapper:mapSources xml:id="id_3">
                    <oracle-xsl-mapper:source type="XSD" xml:id="id_4">
                          <oracle-xsl-mapper:schema location="../../processor_8/resourcegroup_9/ICSSchedule_1.xsd" xml:id="id_5"/>
                          <oracle-xsl-mapper:rootElement name="schedule" namespace="http://www.oracle.com/2014/03/ics/schedule" xml:id="id_6"/>
                    </oracle-xsl-mapper:source>
                    <oracle-xsl-mapper:source type="WSDL" xml:id="id_13">
                          <oracle-xsl-mapper:schema location="../../application_18/inbound_19/resourcegroup_20/getLocation_REQUEST.wsdl" xml:id="id_14"/>
                          <oracle-xsl-mapper:rootElement name="executeResponse" namespace="http://xmlns.oracle.com/cloud/adapter/REST/getLocation_REQUEST/types" xml:id="id_15"/>
                          <oracle-xsl-mapper:param name="getLocation" xml:id="id_16"/>
                    </oracle-xsl-mapper:source>
              </oracle-xsl-mapper:mapSources>
              <oracle-xsl-mapper:mapTargets xml:id="id_7">
                    <oracle-xsl-mapper:target type="WSDL" xml:id="id_8">
                          <oracle-xsl-mapper:schema location="../../processor_41/resourcegroup_42/writeLocationStage_REQUEST.wsdl" xml:id="id_9"/>
                          <oracle-xsl-mapper:rootElement name="Write" namespace="http://xmlns.oracle.com/cloud/adapter/stagefile/writeLocationStage_REQUEST/types" xml:id="id_10"/>
                    </oracle-xsl-mapper:target>
              </oracle-xsl-mapper:mapTargets>
        </oracle-xsl-mapper:schema>
        <xsl:param name="getLocation" xml:id="id_25"/>
        <xsl:param name="lastSyncDate" xml:id="id_61"/>
        <xsl:param name="locationName" xml:id="id_425"/>
        <xsl:template match="/" xml:id="id_11">
              <nstrgmpr:Write xml:id="id_12">
                    <ns25:request-wrapper xml:id="id_32">
                          <xsl:for-each xml:id="id_50" select="$getLocation/nsmpr0:executeResponse/ns23:response-wrapper/ns23:items">
                                <xsl:choose>
                                      <xsl:when test="string-length ($locationName ) = 0">
                                            <xsl:if xml:id="id_237" test="ns23:LastUpdateDate >= $lastSyncDate">
                                                  <ns25:locationDetails xml:id="id_51">
                                                        <ns25:LocationId xml:id="id_240">
                                                              <xsl:value-of xml:id="id_241" select="ns23:LocationId"/>
                                                        </ns25:LocationId>
                                                        <ns25:LocationCode xml:id="id_242">
                                                              <xsl:value-of xml:id="id_243" select="ns23:LocationCode"/>
                                                        </ns25:LocationCode>
                                                        <ns25:LocationName xml:id="id_244">
                                                              <xsl:value-of xml:id="id_245" select="ns23:LocationName"/>
                                                        </ns25:LocationName>
                                                        <ns25:EffectiveStartDate xml:id="id_246">
                                                              <xsl:value-of xml:id="id_247" select="ns23:EffectiveStartDate"/>
                                                        </ns25:EffectiveStartDate>
                                                        <ns25:EffectiveEndDate xml:id="id_248">
                                                              <xsl:value-of xml:id="id_249" select="ns23:EffectiveEndDate"/>
                                                        </ns25:EffectiveEndDate>
                                                        <ns25:ActionReasonId xml:id="id_250">
                                                              <xsl:value-of xml:id="id_251" select="ns23:ActionReasonId"/>
                                                        </ns25:ActionReasonId>
                                                        <ns25:ActionReasonCode xml:id="id_252">
                                                              <xsl:value-of xml:id="id_253" select="ns23:ActionReasonCode"/>
                                                        </ns25:ActionReasonCode>
                                                        <ns25:ActionReason xml:id="id_254">
                                                              <xsl:value-of xml:id="id_255" select="ns23:ActionReason"/>
                                                        </ns25:ActionReason>
                                                        <ns25:ActiveStatus xml:id="id_256">
                                                              <xsl:value-of xml:id="id_257" select="ns23:ActiveStatus"/>
                                                        </ns25:ActiveStatus>
                                                        <ns25:ActiveStatusMeaning xml:id="id_258">
                                                              <xsl:value-of xml:id="id_259" select="ns23:ActiveStatusMeaning"/>
                                                        </ns25:ActiveStatusMeaning>
                                                        <ns25:SetId xml:id="id_260">
                                                              <xsl:value-of xml:id="id_261" select="ns23:SetId"/>
                                                        </ns25:SetId>
                                                        <ns25:SetCode xml:id="id_262">
                                                              <xsl:value-of xml:id="id_263" select="ns23:SetCode"/>
                                                        </ns25:SetCode>
                                                        <ns25:SetName xml:id="id_264">
                                                              <xsl:value-of xml:id="id_265" select="ns23:SetName"/>
                                                        </ns25:SetName>
                                                        <ns25:EmployeeLocationFlag xml:id="id_266">
                                                              <xsl:value-of xml:id="id_267" select="ns23:EmployeeLocationFlag"/>
                                                        </ns25:EmployeeLocationFlag>
                                                        <ns25:Description xml:id="id_268">
                                                              <xsl:value-of xml:id="id_269" select="ns23:Description"/>
                                                        </ns25:Description>
                                                        <ns25:InventoryOrganizationId xml:id="id_270">
                                                              <xsl:value-of xml:id="id_271" select="ns23:InventoryOrganizationId"/>
                                                        </ns25:InventoryOrganizationId>
                                                        <ns25:InventoryOrganizationName xml:id="id_272">
                                                              <xsl:value-of xml:id="id_273" select="ns23:InventoryOrganizationName"/>
                                                        </ns25:InventoryOrganizationName>
                                                        <ns25:OfficialLanguageCode xml:id="id_274">
                                                              <xsl:value-of xml:id="id_275" select="ns23:OfficialLanguageCode"/>
                                                        </ns25:OfficialLanguageCode>
                                                        <ns25:OfficialLanguageMeaning xml:id="id_276">
                                                              <xsl:value-of xml:id="id_277" select="ns23:OfficialLanguageMeaning"/>
                                                        </ns25:OfficialLanguageMeaning>
                                                        <ns25:EmailAddress xml:id="id_278">
                                                              <xsl:value-of xml:id="id_279" select="ns23:EmailAddress"/>
                                                        </ns25:EmailAddress>
                                                        <ns25:GeoHierarchyNodeCode xml:id="id_280">
                                                              <xsl:value-of xml:id="id_281" select="ns23:GeoHierarchyNodeCode"/>
                                                        </ns25:GeoHierarchyNodeCode>
                                                        <ns25:GeoHierarchyNodeName xml:id="id_282">
                                                              <xsl:value-of xml:id="id_283" select="ns23:GeoHierarchyNodeName"/>
                                                        </ns25:GeoHierarchyNodeName>
                                                        <ns25:MainPhoneCountryCode xml:id="id_284">
                                                              <xsl:value-of xml:id="id_285" select="ns23:MainPhoneCountryCode"/>
                                                        </ns25:MainPhoneCountryCode>
                                                        <ns25:MainPhoneAreaCode xml:id="id_286">
                                                              <xsl:value-of xml:id="id_287" select="ns23:MainPhoneAreaCode"/>
                                                        </ns25:MainPhoneAreaCode>
                                                        <ns25:MainPhoneNumber xml:id="id_288">
                                                              <xsl:value-of xml:id="id_289" select="ns23:MainPhoneNumber"/>
                                                        </ns25:MainPhoneNumber>
                                                        <ns25:MainPhoneExtension xml:id="id_290">
                                                              <xsl:value-of xml:id="id_291" select="ns23:MainPhoneExtension"/>
                                                        </ns25:MainPhoneExtension>
                                                        <ns25:FaxCountryCode xml:id="id_292">
                                                              <xsl:value-of xml:id="id_293" select="ns23:FaxCountryCode"/>
                                                        </ns25:FaxCountryCode>
                                                        <ns25:FaxAreaCode xml:id="id_294">
                                                              <xsl:value-of xml:id="id_295" select="ns23:FaxAreaCode"/>
                                                        </ns25:FaxAreaCode>
                                                        <ns25:FaxNumber xml:id="id_296">
                                                              <xsl:value-of xml:id="id_297" select="ns23:FaxNumber"/>
                                                        </ns25:FaxNumber>
                                                        <ns25:FaxExtension xml:id="id_298">
                                                              <xsl:value-of xml:id="id_299" select="ns23:FaxExtension"/>
                                                        </ns25:FaxExtension>
                                                        <ns25:OtherPhoneCountryCode xml:id="id_300">
                                                              <xsl:value-of xml:id="id_301" select="ns23:OtherPhoneCountryCode"/>
                                                        </ns25:OtherPhoneCountryCode>
                                                        <ns25:OtherPhoneAreaCode xml:id="id_302">
                                                              <xsl:value-of xml:id="id_303" select="ns23:OtherPhoneAreaCode"/>
                                                        </ns25:OtherPhoneAreaCode>
                                                        <ns25:OtherPhoneNumber xml:id="id_304">
                                                              <xsl:value-of xml:id="id_305" select="ns23:OtherPhoneNumber"/>
                                                        </ns25:OtherPhoneNumber>
                                                        <ns25:OtherPhoneExtension xml:id="id_306">
                                                              <xsl:value-of xml:id="id_307" select="ns23:OtherPhoneExtension"/>
                                                        </ns25:OtherPhoneExtension>
                                                        <ns25:ShipToSiteFlag xml:id="id_308">
                                                              <xsl:value-of xml:id="id_309" select="ns23:ShipToSiteFlag"/>
                                                        </ns25:ShipToSiteFlag>
                                                        <ns25:ShipToLocationId xml:id="id_310">
                                                              <xsl:value-of xml:id="id_311" select="ns23:ShipToLocationId"/>
                                                        </ns25:ShipToLocationId>
                                                        <ns25:ShipToLocationCode xml:id="id_312">
                                                              <xsl:value-of xml:id="id_313" select="ns23:ShipToLocationCode"/>
                                                        </ns25:ShipToLocationCode>
                                                        <ns25:ShipToLocationName xml:id="id_314">
                                                              <xsl:value-of xml:id="id_315" select="ns23:ShipToLocationName"/>
                                                        </ns25:ShipToLocationName>
                                                        <ns25:OfficeSiteFlag xml:id="id_316">
                                                              <xsl:value-of xml:id="id_317" select="ns23:OfficeSiteFlag"/>
                                                        </ns25:OfficeSiteFlag>
                                                        <ns25:BillToSiteFlag xml:id="id_318">
                                                              <xsl:value-of xml:id="id_319" select="ns23:BillToSiteFlag"/>
                                                        </ns25:BillToSiteFlag>
                                                        <ns25:ReceivingSiteFlag xml:id="id_320">
                                                              <xsl:value-of xml:id="id_321" select="ns23:ReceivingSiteFlag"/>
                                                        </ns25:ReceivingSiteFlag>
                                                        <ns25:DesignatedReceiverId xml:id="id_322">
                                                              <xsl:value-of xml:id="id_323" select="ns23:DesignatedReceiverId"/>
                                                        </ns25:DesignatedReceiverId>
                                                        <ns25:DesignatedReceiverNumber xml:id="id_324">
                                                              <xsl:value-of xml:id="id_325" select="ns23:DesignatedReceiverNumber"/>
                                                        </ns25:DesignatedReceiverNumber>
                                                        <ns25:DesignatedReceiverName xml:id="id_326">
                                                              <xsl:value-of xml:id="id_327" select="ns23:DesignatedReceiverName"/>
                                                        </ns25:DesignatedReceiverName>
                                                        <ns25:CreatedBy xml:id="id_328">
                                                              <xsl:value-of xml:id="id_329" select="ns23:CreatedBy"/>
                                                        </ns25:CreatedBy>
                                                        <ns25:CreationDate xml:id="id_330">
                                                              <xsl:value-of xml:id="id_331" select="ns23:CreationDate"/>
                                                        </ns25:CreationDate>
                                                        <ns25:LastUpdatedBy xml:id="id_332">
                                                              <xsl:value-of xml:id="id_333" select="ns23:LastUpdatedBy"/>
                                                        </ns25:LastUpdatedBy>
                                                        <ns25:LastUpdateDate xml:id="id_334">
                                                              <xsl:value-of xml:id="id_335" select="ns23:LastUpdateDate"/>
                                                        </ns25:LastUpdateDate>
                                                        <ns25:StandardWorkingHours xml:id="id_336">
                                                              <xsl:value-of xml:id="id_337" select="ns23:StandardWorkingHours"/>
                                                        </ns25:StandardWorkingHours>
                                                        <ns25:StandardWorkingFrequency xml:id="id_338">
                                                              <xsl:value-of xml:id="id_339" select="ns23:StandardWorkingFrequency"/>
                                                        </ns25:StandardWorkingFrequency>
                                                        <ns25:StandardWorkingFrequencyMeaning xml:id="id_340">
                                                              <xsl:value-of xml:id="id_341" select="ns23:StandardWorkingFrequencyMeaning"/>
                                                        </ns25:StandardWorkingFrequencyMeaning>
                                                        <ns25:StandardAnnualWorkingDuration xml:id="id_342">
                                                              <xsl:value-of xml:id="id_343" select="ns23:StandardAnnualWorkingDuration"/>
                                                        </ns25:StandardAnnualWorkingDuration>
                                                        <ns25:AnnualWorkingDurationUnits xml:id="id_344">
                                                              <xsl:value-of xml:id="id_345" select="ns23:AnnualWorkingDurationUnits"/>
                                                        </ns25:AnnualWorkingDurationUnits>
                                                        <ns25:AnnualWorkingDurationUnitsMeaning xml:id="id_346">
                                                              <xsl:value-of xml:id="id_347" select="ns23:AnnualWorkingDurationUnitsMeaning"/>
                                                        </ns25:AnnualWorkingDurationUnitsMeaning>
                                                        <xsl:for-each xml:id="id_348" select="ns23:addresses">
                                                              <ns25:addresses xml:id="id_349">
                                                                    <ns25:EffectiveStartDate xml:id="id_350">
                                                                          <xsl:value-of xml:id="id_351" select="ns23:EffectiveStartDate"/>
                                                                    </ns25:EffectiveStartDate>
                                                                    <ns25:EffectiveEndDate xml:id="id_352">
                                                                          <xsl:value-of xml:id="id_353" select="ns23:EffectiveEndDate"/>
                                                                    </ns25:EffectiveEndDate>
                                                                    <ns25:AddressLine1 xml:id="id_354">
                                                                          <xsl:value-of xml:id="id_355" select="ns23:AddressLine1"/>
                                                                    </ns25:AddressLine1>
                                                                    <ns25:AddressLine2 xml:id="id_356">
                                                                          <xsl:value-of xml:id="id_357" select="ns23:AddressLine2"/>
                                                                    </ns25:AddressLine2>
                                                                    <ns25:AddressLine3 xml:id="id_358">
                                                                          <xsl:value-of xml:id="id_359" select="ns23:AddressLine3"/>
                                                                    </ns25:AddressLine3>
                                                                    <ns25:AddressLine4 xml:id="id_360">
                                                                          <xsl:value-of xml:id="id_361" select="ns23:AddressLine4"/>
                                                                    </ns25:AddressLine4>
                                                                    <ns25:TownOrCity xml:id="id_362">
                                                                          <xsl:value-of xml:id="id_363" select="ns23:TownOrCity"/>
                                                                    </ns25:TownOrCity>
                                                                    <ns25:Region1 xml:id="id_364">
                                                                          <xsl:value-of xml:id="id_365" select="ns23:Region1"/>
                                                                    </ns25:Region1>
                                                                    <ns25:Region2 xml:id="id_366">
                                                                          <xsl:value-of xml:id="id_367" select="ns23:Region2"/>
                                                                    </ns25:Region2>
                                                                    <ns25:Region3 xml:id="id_368">
                                                                          <xsl:value-of xml:id="id_369" select="ns23:Region3"/>
                                                                    </ns25:Region3>
                                                                    <ns25:Country xml:id="id_370">
                                                                          <xsl:value-of xml:id="id_371" select="ns23:Country"/>
                                                                    </ns25:Country>
                                                                    <ns25:PostalCode xml:id="id_372">
                                                                          <xsl:value-of xml:id="id_373" select="ns23:PostalCode"/>
                                                                    </ns25:PostalCode>
                                                                    <ns25:LongPostalCode xml:id="id_374">
                                                                          <xsl:value-of xml:id="id_375" select="ns23:LongPostalCode"/>
                                                                    </ns25:LongPostalCode>
                                                                    <ns25:AddlAddressAttribute1 xml:id="id_376">
                                                                          <xsl:value-of xml:id="id_377" select="ns23:AddlAddressAttribute1"/>
                                                                    </ns25:AddlAddressAttribute1>
                                                                    <ns25:AddlAddressAttribute2 xml:id="id_378">
                                                                          <xsl:value-of xml:id="id_379" select="ns23:AddlAddressAttribute2"/>
                                                                    </ns25:AddlAddressAttribute2>
                                                                    <ns25:AddlAddressAttribute3 xml:id="id_380">
                                                                          <xsl:value-of xml:id="id_381" select="ns23:AddlAddressAttribute3"/>
                                                                    </ns25:AddlAddressAttribute3>
                                                                    <ns25:AddlAddressAttribute4 xml:id="id_382">
                                                                          <xsl:value-of xml:id="id_383" select="ns23:AddlAddressAttribute4"/>
                                                                    </ns25:AddlAddressAttribute4>
                                                                    <ns25:AddlAddressAttribute5 xml:id="id_384">
                                                                          <xsl:value-of xml:id="id_385" select="ns23:AddlAddressAttribute5"/>
                                                                    </ns25:AddlAddressAttribute5>
                                                                    <ns25:TimezoneCode xml:id="id_386">
                                                                          <xsl:value-of xml:id="id_387" select="ns23:TimezoneCode"/>
                                                                    </ns25:TimezoneCode>
                                                                    <ns25:Building xml:id="id_388">
                                                                          <xsl:value-of xml:id="id_389" select="ns23:Building"/>
                                                                    </ns25:Building>
                                                                    <ns25:FloorNumber xml:id="id_390">
                                                                          <xsl:value-of xml:id="id_391" select="ns23:FloorNumber"/>
                                                                    </ns25:FloorNumber>
                                                                    <ns25:CreatedBy xml:id="id_392">
                                                                          <xsl:value-of xml:id="id_393" select="ns23:CreatedBy"/>
                                                                    </ns25:CreatedBy>
                                                                    <ns25:CreationDate xml:id="id_394">
                                                                          <xsl:value-of xml:id="id_395" select="ns23:CreationDate"/>
                                                                    </ns25:CreationDate>
                                                                    <ns25:LastUpdatedBy xml:id="id_396">
                                                                          <xsl:value-of xml:id="id_397" select="ns23:LastUpdatedBy"/>
                                                                    </ns25:LastUpdatedBy>
                                                                    <ns25:LastUpdateDate xml:id="id_398">
                                                                          <xsl:value-of xml:id="id_399" select="ns23:LastUpdateDate"/>
                                                                    </ns25:LastUpdateDate>
                                                                    <ns25:ValidationStatusCode xml:id="id_400">
                                                                          <xsl:value-of xml:id="id_401" select="ns23:ValidationStatusCode"/>
                                                                    </ns25:ValidationStatusCode>
                                                                    <ns25:Provider xml:id="id_402">
                                                                          <xsl:value-of xml:id="id_403" select="ns23:Provider"/>
                                                                    </ns25:Provider>
                                                                    <ns25:Latitude xml:id="id_404">
                                                                          <xsl:value-of xml:id="id_405" select="ns23:Latitude"/>
                                                                    </ns25:Latitude>
                                                                    <ns25:Longitude xml:id="id_406">
                                                                          <xsl:value-of xml:id="id_407" select="ns23:Longitude"/>
                                                                    </ns25:Longitude>
                                                                    <ns25:Timezone xml:id="id_408">
                                                                          <xsl:value-of xml:id="id_409" select="ns23:Timezone"/>
                                                                    </ns25:Timezone>
                                                                    <ns25:LocAddressUsageId xml:id="id_410">
                                                                          <xsl:value-of xml:id="id_411" select="ns23:LocAddressUsageId"/>
                                                                    </ns25:LocAddressUsageId>
                                                                    <ns25:AddressUsageType xml:id="id_412">
                                                                          <xsl:value-of xml:id="id_413" select="ns23:AddressUsageType"/>
                                                                    </ns25:AddressUsageType>
                                                                    <ns25:AddressUsageTypeMeaning xml:id="id_414">
                                                                          <xsl:value-of xml:id="id_415" select="ns23:AddressUsageTypeMeaning"/>
                                                                    </ns25:AddressUsageTypeMeaning>
                                                              </ns25:addresses>
                                                        </xsl:for-each>
                                                  </ns25:locationDetails>
                                            </xsl:if>
                                      </xsl:when>
                                      <xsl:otherwise>
                                            <ns25:locationDetails xml:id="id_51">
                                                        <ns25:LocationId xml:id="id_240">
                                                              <xsl:value-of xml:id="id_241" select="ns23:LocationId"/>
                                                        </ns25:LocationId>
                                                        <ns25:LocationCode xml:id="id_242">
                                                              <xsl:value-of xml:id="id_243" select="ns23:LocationCode"/>
                                                        </ns25:LocationCode>
                                                        <ns25:LocationName xml:id="id_244">
                                                              <xsl:value-of xml:id="id_245" select="ns23:LocationName"/>
                                                        </ns25:LocationName>
                                                        <ns25:EffectiveStartDate xml:id="id_246">
                                                              <xsl:value-of xml:id="id_247" select="ns23:EffectiveStartDate"/>
                                                        </ns25:EffectiveStartDate>
                                                        <ns25:EffectiveEndDate xml:id="id_248">
                                                              <xsl:value-of xml:id="id_249" select="ns23:EffectiveEndDate"/>
                                                        </ns25:EffectiveEndDate>
                                                        <ns25:ActionReasonId xml:id="id_250">
                                                              <xsl:value-of xml:id="id_251" select="ns23:ActionReasonId"/>
                                                        </ns25:ActionReasonId>
                                                        <ns25:ActionReasonCode xml:id="id_252">
                                                              <xsl:value-of xml:id="id_253" select="ns23:ActionReasonCode"/>
                                                        </ns25:ActionReasonCode>
                                                        <ns25:ActionReason xml:id="id_254">
                                                              <xsl:value-of xml:id="id_255" select="ns23:ActionReason"/>
                                                        </ns25:ActionReason>
                                                        <ns25:ActiveStatus xml:id="id_256">
                                                              <xsl:value-of xml:id="id_257" select="ns23:ActiveStatus"/>
                                                        </ns25:ActiveStatus>
                                                        <ns25:ActiveStatusMeaning xml:id="id_258">
                                                              <xsl:value-of xml:id="id_259" select="ns23:ActiveStatusMeaning"/>
                                                        </ns25:ActiveStatusMeaning>
                                                        <ns25:SetId xml:id="id_260">
                                                              <xsl:value-of xml:id="id_261" select="ns23:SetId"/>
                                                        </ns25:SetId>
                                                        <ns25:SetCode xml:id="id_262">
                                                              <xsl:value-of xml:id="id_263" select="ns23:SetCode"/>
                                                        </ns25:SetCode>
                                                        <ns25:SetName xml:id="id_264">
                                                              <xsl:value-of xml:id="id_265" select="ns23:SetName"/>
                                                        </ns25:SetName>
                                                        <ns25:EmployeeLocationFlag xml:id="id_266">
                                                              <xsl:value-of xml:id="id_267" select="ns23:EmployeeLocationFlag"/>
                                                        </ns25:EmployeeLocationFlag>
                                                        <ns25:Description xml:id="id_268">
                                                              <xsl:value-of xml:id="id_269" select="ns23:Description"/>
                                                        </ns25:Description>
                                                        <ns25:InventoryOrganizationId xml:id="id_270">
                                                              <xsl:value-of xml:id="id_271" select="ns23:InventoryOrganizationId"/>
                                                        </ns25:InventoryOrganizationId>
                                                        <ns25:InventoryOrganizationName xml:id="id_272">
                                                              <xsl:value-of xml:id="id_273" select="ns23:InventoryOrganizationName"/>
                                                        </ns25:InventoryOrganizationName>
                                                        <ns25:OfficialLanguageCode xml:id="id_274">
                                                              <xsl:value-of xml:id="id_275" select="ns23:OfficialLanguageCode"/>
                                                        </ns25:OfficialLanguageCode>
                                                        <ns25:OfficialLanguageMeaning xml:id="id_276">
                                                              <xsl:value-of xml:id="id_277" select="ns23:OfficialLanguageMeaning"/>
                                                        </ns25:OfficialLanguageMeaning>
                                                        <ns25:EmailAddress xml:id="id_278">
                                                              <xsl:value-of xml:id="id_279" select="ns23:EmailAddress"/>
                                                        </ns25:EmailAddress>
                                                        <ns25:GeoHierarchyNodeCode xml:id="id_280">
                                                              <xsl:value-of xml:id="id_281" select="ns23:GeoHierarchyNodeCode"/>
                                                        </ns25:GeoHierarchyNodeCode>
                                                        <ns25:GeoHierarchyNodeName xml:id="id_282">
                                                              <xsl:value-of xml:id="id_283" select="ns23:GeoHierarchyNodeName"/>
                                                        </ns25:GeoHierarchyNodeName>
                                                        <ns25:MainPhoneCountryCode xml:id="id_284">
                                                              <xsl:value-of xml:id="id_285" select="ns23:MainPhoneCountryCode"/>
                                                        </ns25:MainPhoneCountryCode>
                                                        <ns25:MainPhoneAreaCode xml:id="id_286">
                                                              <xsl:value-of xml:id="id_287" select="ns23:MainPhoneAreaCode"/>
                                                        </ns25:MainPhoneAreaCode>
                                                        <ns25:MainPhoneNumber xml:id="id_288">
                                                              <xsl:value-of xml:id="id_289" select="ns23:MainPhoneNumber"/>
                                                        </ns25:MainPhoneNumber>
                                                        <ns25:MainPhoneExtension xml:id="id_290">
                                                              <xsl:value-of xml:id="id_291" select="ns23:MainPhoneExtension"/>
                                                        </ns25:MainPhoneExtension>
                                                        <ns25:FaxCountryCode xml:id="id_292">
                                                              <xsl:value-of xml:id="id_293" select="ns23:FaxCountryCode"/>
                                                        </ns25:FaxCountryCode>
                                                        <ns25:FaxAreaCode xml:id="id_294">
                                                              <xsl:value-of xml:id="id_295" select="ns23:FaxAreaCode"/>
                                                        </ns25:FaxAreaCode>
                                                        <ns25:FaxNumber xml:id="id_296">
                                                              <xsl:value-of xml:id="id_297" select="ns23:FaxNumber"/>
                                                        </ns25:FaxNumber>
                                                        <ns25:FaxExtension xml:id="id_298">
                                                              <xsl:value-of xml:id="id_299" select="ns23:FaxExtension"/>
                                                        </ns25:FaxExtension>
                                                        <ns25:OtherPhoneCountryCode xml:id="id_300">
                                                              <xsl:value-of xml:id="id_301" select="ns23:OtherPhoneCountryCode"/>
                                                        </ns25:OtherPhoneCountryCode>
                                                        <ns25:OtherPhoneAreaCode xml:id="id_302">
                                                              <xsl:value-of xml:id="id_303" select="ns23:OtherPhoneAreaCode"/>
                                                        </ns25:OtherPhoneAreaCode>
                                                        <ns25:OtherPhoneNumber xml:id="id_304">
                                                              <xsl:value-of xml:id="id_305" select="ns23:OtherPhoneNumber"/>
                                                        </ns25:OtherPhoneNumber>
                                                        <ns25:OtherPhoneExtension xml:id="id_306">
                                                              <xsl:value-of xml:id="id_307" select="ns23:OtherPhoneExtension"/>
                                                        </ns25:OtherPhoneExtension>
                                                        <ns25:ShipToSiteFlag xml:id="id_308">
                                                              <xsl:value-of xml:id="id_309" select="ns23:ShipToSiteFlag"/>
                                                        </ns25:ShipToSiteFlag>
                                                        <ns25:ShipToLocationId xml:id="id_310">
                                                              <xsl:value-of xml:id="id_311" select="ns23:ShipToLocationId"/>
                                                        </ns25:ShipToLocationId>
                                                        <ns25:ShipToLocationCode xml:id="id_312">
                                                              <xsl:value-of xml:id="id_313" select="ns23:ShipToLocationCode"/>
                                                        </ns25:ShipToLocationCode>
                                                        <ns25:ShipToLocationName xml:id="id_314">
                                                              <xsl:value-of xml:id="id_315" select="ns23:ShipToLocationName"/>
                                                        </ns25:ShipToLocationName>
                                                        <ns25:OfficeSiteFlag xml:id="id_316">
                                                              <xsl:value-of xml:id="id_317" select="ns23:OfficeSiteFlag"/>
                                                        </ns25:OfficeSiteFlag>
                                                        <ns25:BillToSiteFlag xml:id="id_318">
                                                              <xsl:value-of xml:id="id_319" select="ns23:BillToSiteFlag"/>
                                                        </ns25:BillToSiteFlag>
                                                        <ns25:ReceivingSiteFlag xml:id="id_320">
                                                              <xsl:value-of xml:id="id_321" select="ns23:ReceivingSiteFlag"/>
                                                        </ns25:ReceivingSiteFlag>
                                                        <ns25:DesignatedReceiverId xml:id="id_322">
                                                              <xsl:value-of xml:id="id_323" select="ns23:DesignatedReceiverId"/>
                                                        </ns25:DesignatedReceiverId>
                                                        <ns25:DesignatedReceiverNumber xml:id="id_324">
                                                              <xsl:value-of xml:id="id_325" select="ns23:DesignatedReceiverNumber"/>
                                                        </ns25:DesignatedReceiverNumber>
                                                        <ns25:DesignatedReceiverName xml:id="id_326">
                                                              <xsl:value-of xml:id="id_327" select="ns23:DesignatedReceiverName"/>
                                                        </ns25:DesignatedReceiverName>
                                                        <ns25:CreatedBy xml:id="id_328">
                                                              <xsl:value-of xml:id="id_329" select="ns23:CreatedBy"/>
                                                        </ns25:CreatedBy>
                                                        <ns25:CreationDate xml:id="id_330">
                                                              <xsl:value-of xml:id="id_331" select="ns23:CreationDate"/>
                                                        </ns25:CreationDate>
                                                        <ns25:LastUpdatedBy xml:id="id_332">
                                                              <xsl:value-of xml:id="id_333" select="ns23:LastUpdatedBy"/>
                                                        </ns25:LastUpdatedBy>
                                                        <ns25:LastUpdateDate xml:id="id_334">
                                                              <xsl:value-of xml:id="id_335" select="ns23:LastUpdateDate"/>
                                                        </ns25:LastUpdateDate>
                                                        <ns25:StandardWorkingHours xml:id="id_336">
                                                              <xsl:value-of xml:id="id_337" select="ns23:StandardWorkingHours"/>
                                                        </ns25:StandardWorkingHours>
                                                        <ns25:StandardWorkingFrequency xml:id="id_338">
                                                              <xsl:value-of xml:id="id_339" select="ns23:StandardWorkingFrequency"/>
                                                        </ns25:StandardWorkingFrequency>
                                                        <ns25:StandardWorkingFrequencyMeaning xml:id="id_340">
                                                              <xsl:value-of xml:id="id_341" select="ns23:StandardWorkingFrequencyMeaning"/>
                                                        </ns25:StandardWorkingFrequencyMeaning>
                                                        <ns25:StandardAnnualWorkingDuration xml:id="id_342">
                                                              <xsl:value-of xml:id="id_343" select="ns23:StandardAnnualWorkingDuration"/>
                                                        </ns25:StandardAnnualWorkingDuration>
                                                        <ns25:AnnualWorkingDurationUnits xml:id="id_344">
                                                              <xsl:value-of xml:id="id_345" select="ns23:AnnualWorkingDurationUnits"/>
                                                        </ns25:AnnualWorkingDurationUnits>
                                                        <ns25:AnnualWorkingDurationUnitsMeaning xml:id="id_346">
                                                              <xsl:value-of xml:id="id_347" select="ns23:AnnualWorkingDurationUnitsMeaning"/>
                                                        </ns25:AnnualWorkingDurationUnitsMeaning>
                                                        <xsl:for-each xml:id="id_348" select="ns23:addresses">
                                                              <ns25:addresses xml:id="id_349">
                                                                    <ns25:EffectiveStartDate xml:id="id_350">
                                                                          <xsl:value-of xml:id="id_351" select="ns23:EffectiveStartDate"/>
                                                                    </ns25:EffectiveStartDate>
                                                                    <ns25:EffectiveEndDate xml:id="id_352">
                                                                          <xsl:value-of xml:id="id_353" select="ns23:EffectiveEndDate"/>
                                                                    </ns25:EffectiveEndDate>
                                                                    <ns25:AddressLine1 xml:id="id_354">
                                                                          <xsl:value-of xml:id="id_355" select="ns23:AddressLine1"/>
                                                                    </ns25:AddressLine1>
                                                                    <ns25:AddressLine2 xml:id="id_356">
                                                                          <xsl:value-of xml:id="id_357" select="ns23:AddressLine2"/>
                                                                    </ns25:AddressLine2>
                                                                    <ns25:AddressLine3 xml:id="id_358">
                                                                          <xsl:value-of xml:id="id_359" select="ns23:AddressLine3"/>
                                                                    </ns25:AddressLine3>
                                                                    <ns25:AddressLine4 xml:id="id_360">
                                                                          <xsl:value-of xml:id="id_361" select="ns23:AddressLine4"/>
                                                                    </ns25:AddressLine4>
                                                                    <ns25:TownOrCity xml:id="id_362">
                                                                          <xsl:value-of xml:id="id_363" select="ns23:TownOrCity"/>
                                                                    </ns25:TownOrCity>
                                                                    <ns25:Region1 xml:id="id_364">
                                                                          <xsl:value-of xml:id="id_365" select="ns23:Region1"/>
                                                                    </ns25:Region1>
                                                                    <ns25:Region2 xml:id="id_366">
                                                                          <xsl:value-of xml:id="id_367" select="ns23:Region2"/>
                                                                    </ns25:Region2>
                                                                    <ns25:Region3 xml:id="id_368">
                                                                          <xsl:value-of xml:id="id_369" select="ns23:Region3"/>
                                                                    </ns25:Region3>
                                                                    <ns25:Country xml:id="id_370">
                                                                          <xsl:value-of xml:id="id_371" select="ns23:Country"/>
                                                                    </ns25:Country>
                                                                    <ns25:PostalCode xml:id="id_372">
                                                                          <xsl:value-of xml:id="id_373" select="ns23:PostalCode"/>
                                                                    </ns25:PostalCode>
                                                                    <ns25:LongPostalCode xml:id="id_374">
                                                                          <xsl:value-of xml:id="id_375" select="ns23:LongPostalCode"/>
                                                                    </ns25:LongPostalCode>
                                                                    <ns25:AddlAddressAttribute1 xml:id="id_376">
                                                                          <xsl:value-of xml:id="id_377" select="ns23:AddlAddressAttribute1"/>
                                                                    </ns25:AddlAddressAttribute1>
                                                                    <ns25:AddlAddressAttribute2 xml:id="id_378">
                                                                          <xsl:value-of xml:id="id_379" select="ns23:AddlAddressAttribute2"/>
                                                                    </ns25:AddlAddressAttribute2>
                                                                    <ns25:AddlAddressAttribute3 xml:id="id_380">
                                                                          <xsl:value-of xml:id="id_381" select="ns23:AddlAddressAttribute3"/>
                                                                    </ns25:AddlAddressAttribute3>
                                                                    <ns25:AddlAddressAttribute4 xml:id="id_382">
                                                                          <xsl:value-of xml:id="id_383" select="ns23:AddlAddressAttribute4"/>
                                                                    </ns25:AddlAddressAttribute4>
                                                                    <ns25:AddlAddressAttribute5 xml:id="id_384">
                                                                          <xsl:value-of xml:id="id_385" select="ns23:AddlAddressAttribute5"/>
                                                                    </ns25:AddlAddressAttribute5>
                                                                    <ns25:TimezoneCode xml:id="id_386">
                                                                          <xsl:value-of xml:id="id_387" select="ns23:TimezoneCode"/>
                                                                    </ns25:TimezoneCode>
                                                                    <ns25:Building xml:id="id_388">
                                                                          <xsl:value-of xml:id="id_389" select="ns23:Building"/>
                                                                    </ns25:Building>
                                                                    <ns25:FloorNumber xml:id="id_390">
                                                                          <xsl:value-of xml:id="id_391" select="ns23:FloorNumber"/>
                                                                    </ns25:FloorNumber>
                                                                    <ns25:CreatedBy xml:id="id_392">
                                                                          <xsl:value-of xml:id="id_393" select="ns23:CreatedBy"/>
                                                                    </ns25:CreatedBy>
                                                                    <ns25:CreationDate xml:id="id_394">
                                                                          <xsl:value-of xml:id="id_395" select="ns23:CreationDate"/>
                                                                    </ns25:CreationDate>
                                                                    <ns25:LastUpdatedBy xml:id="id_396">
                                                                          <xsl:value-of xml:id="id_397" select="ns23:LastUpdatedBy"/>
                                                                    </ns25:LastUpdatedBy>
                                                                    <ns25:LastUpdateDate xml:id="id_398">
                                                                          <xsl:value-of xml:id="id_399" select="ns23:LastUpdateDate"/>
                                                                    </ns25:LastUpdateDate>
                                                                    <ns25:ValidationStatusCode xml:id="id_400">
                                                                          <xsl:value-of xml:id="id_401" select="ns23:ValidationStatusCode"/>
                                                                    </ns25:ValidationStatusCode>
                                                                    <ns25:Provider xml:id="id_402">
                                                                          <xsl:value-of xml:id="id_403" select="ns23:Provider"/>
                                                                    </ns25:Provider>
                                                                    <ns25:Latitude xml:id="id_404">
                                                                          <xsl:value-of xml:id="id_405" select="ns23:Latitude"/>
                                                                    </ns25:Latitude>
                                                                    <ns25:Longitude xml:id="id_406">
                                                                          <xsl:value-of xml:id="id_407" select="ns23:Longitude"/>
                                                                    </ns25:Longitude>
                                                                    <ns25:Timezone xml:id="id_408">
                                                                          <xsl:value-of xml:id="id_409" select="ns23:Timezone"/>
                                                                    </ns25:Timezone>
                                                                    <ns25:LocAddressUsageId xml:id="id_410">
                                                                          <xsl:value-of xml:id="id_411" select="ns23:LocAddressUsageId"/>
                                                                    </ns25:LocAddressUsageId>
                                                                    <ns25:AddressUsageType xml:id="id_412">
                                                                          <xsl:value-of xml:id="id_413" select="ns23:AddressUsageType"/>
                                                                    </ns25:AddressUsageType>
                                                                    <ns25:AddressUsageTypeMeaning xml:id="id_414">
                                                                          <xsl:value-of xml:id="id_415" select="ns23:AddressUsageTypeMeaning"/>
                                                                    </ns25:AddressUsageTypeMeaning>
                                                              </ns25:addresses>
                                                        </xsl:for-each>
                                                  </ns25:locationDetails>
                                      </xsl:otherwise>
                                </xsl:choose>
                          </xsl:for-each>
                    </ns25:request-wrapper>
              </nstrgmpr:Write>
        </xsl:template>
  </xsl:stylesheet>